apiVersion: v1
kind: Service
metadata:
  name: mon
  namespace: __namespace__
spec:
  type: ClusterIP
  selector:
    app: mon
  ports:
    - protocol: TCP
      port: 80
      targetPort: 10005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon
  namespace: __namespace__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mon
  template:
    metadata:
      labels:
        app: mon
    spec:
      containers:
        - name: mon
          image: '__docker_registry_server__/datanimbus.io.mon:__release__'
          ports:
            - containerPort: 10005
          livenessProbe:
            httpGet:
              path: /mon/health/live
              port: 10005
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /mon/health/ready
              port: 10005
            initialDelaySeconds: 10
            periodSeconds: 10
          envFrom:
          - configMapRef:
              name: config
      imagePullSecrets:
        - name: regsecret        

